
const SUCCESS_CREATED_STATUS = 201;
const SUCCESS_RETREIVED_STATUS = 200;
const SERVER_ERROR = 500;
const UNAUTHORIZED_STATUS = 401;
const BAD_REQUEST = 400;
const STATUS_NOT_FOUND = 404;

module.exports.http_constants = {
    SUCCESS_CREATED_STATUS,
    SUCCESS_RETREIVED_STATUS,
    SERVER_ERROR,
    UNAUTHORIZED_STATUS,
    BAD_REQUEST,
    STATUS_NOT_FOUND
    
}